// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAc05Hvo7Dk20kUj7KGJ6s1W1YBbAcJEQ',
    appId: '1:545589373174:web:b231b5a9d3f9019d1b24d7',
    messagingSenderId: '545589373174',
    projectId: 'micelioapp',
    authDomain: 'micelioapp.firebaseapp.com',
    storageBucket: 'micelioapp.appspot.com',
    measurementId: 'G-LYS50VLYP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0GR592RXnpSZcYfWUuLHziXA4Nhd8rQ',
    appId: '1:545589373174:android:8de98762255d84ce1b24d7',
    messagingSenderId: '545589373174',
    projectId: 'micelioapp',
    storageBucket: 'micelioapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdk2LMyHc9AB_wK7ENlyQTnMDRl8hutU',
    appId: '1:545589373174:ios:e34b724e6d8c5b2d1b24d7',
    messagingSenderId: '545589373174',
    projectId: 'micelioapp',
    storageBucket: 'micelioapp.appspot.com',
    iosBundleId: 'com.example.micelioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmdk2LMyHc9AB_wK7ENlyQTnMDRl8hutU',
    appId: '1:545589373174:ios:e34b724e6d8c5b2d1b24d7',
    messagingSenderId: '545589373174',
    projectId: 'micelioapp',
    storageBucket: 'micelioapp.appspot.com',
    iosBundleId: 'com.example.micelioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAc05Hvo7Dk20kUj7KGJ6s1W1YBbAcJEQ',
    appId: '1:545589373174:web:b231b5a9d3f9019d1b24d7',
    messagingSenderId: '545589373174',
    projectId: 'micelioapp',
    authDomain: 'micelioapp.firebaseapp.com',
    storageBucket: 'micelioapp.appspot.com',
    measurementId: 'G-LYS50VLYP8',
  );

}